spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
<<<<<<< Updated upstream
<<<<<<< Updated upstream
<<<<<<< Updated upstream
      ddl-auto: create-drop
=======
      ddl-auto: update
>>>>>>> Stashed changes
=======
      ddl-auto: update
>>>>>>> Stashed changes
=======
      ddl-auto: update
>>>>>>> Stashed changes
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/finConnect-db
    username: finConnect-master
    password: root
  security:
    user:
      name: finConnect-master
      password: root

jwt:
  secret-key: VrOV7qcBRFy82Ueg1bJQXVBj5tl4blpR1234567890abcdef

logging:
  level:
    root: warn
    org:
      springframework:
        security:
          web:
            FilterChainProxy: trace
          authorization:
            RequestMatcherDelegatingAuthorizationManager: trace
            authentication:
              ExceptionTranslationFilter: trace

#    org.hibernate.type: warn
#    org.hibernate.orm.jdbc.bind: warn
#    org.hibernate.engine.transaction.internal.TransactionImpl: warn
#    org.springframework.orm.jpa: warn
#    org.springframework.transaction: warn

